// Code generated by "stringer -type Type"; DO NOT EDIT.

package metric

import "strconv"

const _Type_name = "TypeGaugeInt64TypeGaugeDoubleTypeGaugeDistributionTypeCumulativeInt64TypeCumulativeDoubleTypeCumulativeDistributionTypeSummary"

var _Type_index = [...]uint8{0, 14, 29, 50, 69, 89, 115, 126}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
