// Code generated by "stringer -type ValueType"; DO NOT EDIT.

package metric

import "strconv"

const _ValueType_name = "ValueTypeDoubleValueTypeInt64ValueTypeDistributionValueTypeSummary"

var _ValueType_index = [...]uint8{0, 15, 29, 50, 66}

func (i ValueType) String() string {
	if i < 0 || i >= ValueType(len(_ValueType_index)-1) {
		return "ValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueType_name[_ValueType_index[i]:_ValueType_index[i+1]]
}
