// Code generated by protoc-gen-go.
// source: github.com/google/instrumentation-go/grpc-plugin-app-sample/sample.proto
// DO NOT EDIT!

/*
Package sample is a generated protocol buffer package.

It is generated from these files:
	github.com/google/instrumentation-go/grpc-plugin-app-sample/sample.proto

It has these top-level messages:
	HelloRequest
	HelloReply
*/
package sample

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "HelloReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// Sends a greeting stream
	SayHelloStream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayHelloStreamClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHelloStream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayHelloStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Greeter_serviceDesc.Streams[0], c.cc, "/Greeter/SayHelloStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHelloStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SayHelloStreamClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayHelloStreamClient struct {
	grpc.ClientStream
}

func (x *greeterSayHelloStreamClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// Sends a greeting stream
	SayHelloStream(*HelloRequest, Greeter_SayHelloStreamServer) error
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHelloStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SayHelloStream(m, &greeterSayHelloStreamServer{stream})
}

type Greeter_SayHelloStreamServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSayHelloStreamServer struct {
	grpc.ServerStream
}

func (x *greeterSayHelloStreamServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHelloStream",
			Handler:       _Greeter_SayHelloStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "github.com/google/instrumentation-go/grpc-plugin-app-sample/sample.proto",
}

func init() {
	proto.RegisterFile("github.com/google/instrumentation-go/grpc-plugin-app-sample/sample.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0xce, 0x3d, 0x4e, 0xc5, 0x30,
	0x0c, 0x07, 0x70, 0x2a, 0x21, 0x1e, 0x98, 0x8f, 0x21, 0xd3, 0x13, 0x13, 0xca, 0x80, 0xba, 0x24,
	0xa9, 0xe0, 0x10, 0x74, 0x6e, 0x4f, 0x90, 0x56, 0x56, 0x88, 0x94, 0xc4, 0x21, 0x71, 0x86, 0xde,
	0x1e, 0xa9, 0x50, 0xc1, 0xf4, 0x26, 0xdb, 0xd2, 0xcf, 0xf6, 0x1f, 0x46, 0xe7, 0xf9, 0xb3, 0x2d,
	0x7a, 0xa5, 0x68, 0x1c, 0x91, 0x0b, 0x68, 0x7c, 0xaa, 0x5c, 0x5a, 0xc4, 0xc4, 0x96, 0x3d, 0x25,
	0xe5, 0xc8, 0xb8, 0x92, 0x57, 0x95, 0x43, 0x73, 0x3e, 0x29, 0x9b, 0xb3, 0xaa, 0x36, 0xe6, 0x80,
	0xe6, 0xa7, 0xe8, 0x5c, 0x88, 0x49, 0x4a, 0x78, 0x18, 0x31, 0x04, 0x9a, 0xf0, 0xab, 0x61, 0x65,
	0x21, 0xe0, 0x3a, 0xd9, 0x88, 0xe7, 0xee, 0xa5, 0xeb, 0xef, 0xa6, 0xbd, 0x97, 0xaf, 0x00, 0xbf,
	0x26, 0x87, 0x4d, 0x9c, 0xe1, 0x14, 0xb1, 0x56, 0xeb, 0x0e, 0x74, 0x8c, 0x6f, 0x08, 0xa7, 0x8f,
	0x82, 0xc8, 0x58, 0x44, 0x0f, 0xb7, 0xb3, 0xdd, 0xf6, 0x2d, 0xf1, 0xa8, 0xff, 0x7f, 0x78, 0xbe,
	0xd7, 0x7f, 0xc7, 0xe4, 0x95, 0x18, 0xe0, 0xe9, 0x90, 0x33, 0x17, 0xb4, 0xf1, 0xb2, 0x1f, 0xba,
	0xe5, 0x66, 0x4f, 0xfe, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x91, 0x9c, 0x7c, 0x71, 0x05, 0x01,
	0x00, 0x00,
}
